Parse error message instead of return code

diff --git a/.github/workflows/benchmark.yml b/.github/workflows/benchmark.yml
--- a/.github/workflows/benchmark.yml
+++ b/.github/workflows/benchmark.yml
@@ -74,9 +74,6 @@ jobs:
       - name: Pull request comment text
         id: benchmark-comment
         run: |
-          echo '---' >> $GITHUB_STEP_SUMMARY
-          swift package benchmark baseline compare main pull_request --no-progress --quiet --format markdown >> $GITHUB_STEP_SUMMARY
-
           echo "[Pull request benchmark comparison [${{ matrix.os }}] with 'main' run at $(date -Iseconds)](https://github.com/adam-fowler/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }})" >> comment.md
 
           EXIT_CODE='${{steps.benchmark.outputs.exit-status}}'
@@ -87,23 +84,28 @@ jobs:
               echo "_Pull request no significant performance differences ✅_" >> comment.md
               echo "exitStatus=0" >> $GITHUB_ENV
               ;;
-            1)
-              echo "_Pull request has significant performance differences_" >> comment.md
-              echo "exitStatus=1" >> $GITHUB_ENV
-              ;;
-            2)
-              echo "_Pull request has performance regressions ❌_" >> comment.md
-              echo "exitStatus=1" >> $GITHUB_ENV
-              ;;
-            4)
-              echo "_Pull request has performance improvements ✅_" >> comment.md
-              echo "exitStatus=0" >> $GITHUB_ENV
-              ;;
             *)
-              echo "_Benchmark comparison failed to complete with exit code $EXIT_CODE ❌_" >> comment.md
-              echo "exitStatus=1" >> $GITHUB_ENV
+              # Get error string from benchmark output
+              BENCHMARK_ERROR=echo $GITHUB_STEP_SUMMARY | grep -e "^error:.*" | tail -n 1 | cut -f 2 -w
+              case "${BENCHMARK_ERROR}" in
+                "benchmarkThresholdRegression")
+                  echo "_Pull request has performance regressions ❌_" >> comment.md
+                  echo "exitStatus=1" >> $GITHUB_ENV
+                  ;;
+                "benchmarkThresholdImprovement")
+                  echo "_Pull request has performance improvements ✅_" >> comment.md
+                  echo "exitStatus=0" >> $GITHUB_ENV
+                  ;;
+                *)
+                  echo "_Benchmark comparison failed with error $BENCHMARK_ERROR ❌_" >> comment.md
+                  echo "exitStatus=1" >> $GITHUB_ENV
+                  ;;
+              esac
               ;;
           esac
+
+          echo '---' >> $GITHUB_STEP_SUMMARY
+          swift package benchmark baseline compare main pull_request --no-progress --quiet --format markdown >> $GITHUB_STEP_SUMMARY
       - name: Comment PR
         if: ${{ env.hasBenchmark == '1' }}
         uses: thollander/actions-comment-pull-request@v3
@@ -113,4 +115,4 @@ jobs:
           comment-tag: benchmark
       - name: Exit with correct status
         run: |
-          exit 0
+          exit ${exitStatus}
