with output

diff --git a/.github/workflows/benchmark.yml b/.github/workflows/benchmark.yml
--- a/.github/workflows/benchmark.yml
+++ b/.github/workflows/benchmark.yml
@@ -68,12 +68,14 @@ jobs:
           echo '## Summary' >> $GITHUB_STEP_SUMMARY
           echo $(date) >> $GITHUB_STEP_SUMMARY
           set +e
-          # if we had access to fd 3 we could do this in one call but unfortunately we dont so we have to run
-          # the baseline check twice once to extract stdout and once to extract stderr
-          benchmark-stderr=$(swift package benchmark baseline check main pull_request 2>&1)
+          # if we had access to fd 3 we could do this in one call eg { var=$(cmd 3>&2 2>&1 1>&3); }  2>&1
+          # but unfortunately we don't so we have to run the baseline check twice once to extract stdout 
+          # and once to extract stderr
+          BENCHMARK_STDERR=$(swift package benchmark baseline check main pull_request 2>&1)
           swift package benchmark baseline check main pull_request --format markdown >> $GITHUB_STEP_SUMMARY
           echo "exit-status=$?" >> $GITHUB_OUTPUT
-          echo "benchmark-error=$(echo -e "$benchmark-stderr" | grep -e "^error: .*" | tail -n 1 | cut -c 8-)" >> $GITHUB_OUTPUT
+          echo "benchmark-error=$(echo -e "$BENCHMARK_STDERR" | grep -e "^error: .*" | tail -n 1 | cut -c 8-)"
+          echo "benchmark-error=$(echo -e "$BENCHMARK_STDERR" | grep -e "^error: .*" | tail -n 1 | cut -c 8-)" >> $GITHUB_OUTPUT
           set -e
       - name: Pull request comment text
         id: benchmark-comment
