minor edits

diff --git a/.github/workflows/benchmark.yml b/.github/workflows/benchmark.yml
--- a/.github/workflows/benchmark.yml
+++ b/.github/workflows/benchmark.yml
@@ -68,7 +68,7 @@ jobs:
           echo '## Summary' >> $GITHUB_STEP_SUMMARY
           echo $(date) >> $GITHUB_STEP_SUMMARY
           swift package benchmark baseline check main pull_request --format markdown >> $GITHUB_STEP_SUMMARY
-          echo "exit-status=$?" >> "${GITHUB_OUTPUT}"
+          echo "exit-status=$?" >> $GITHUB_OUTPUT
         continue-on-error: true
       - name: Pull request comment text
         id: benchmark-comment
@@ -78,27 +78,28 @@ jobs:
 
           echo "[Pull request benchmark comparison [${{ matrix.os }}] with 'main' run at $(date -Iseconds)](https://github.com/adam-fowler/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }})" >> comment.md
 
-          EXIT_CODE=${{steps.benchmark.outputs.exit-status}}
+          EXIT_CODE='${{steps.benchmark.outputs.exit-status}}'
           echo "Exit code $EXIT_CODE"
 
           case "${EXIT_CODE}" in
             0)
+              echo "_Pull request no significant performance differences ✅_" >> comment.md
               echo "exitStatus=0" >> $GITHUB_ENV
               ;;
             1)
-              echo "_Pull request has significant differences_" >> comment.md
+              echo "_Pull request has significant performance differences ❌_" >> comment.md
               echo "exitStatus=1" >> $GITHUB_ENV
               ;;
             2)
-              echo "_Pull request has performance regressions_" >> comment.md
+              echo "_Pull request has performance regressions ❌_" >> comment.md
               echo "exitStatus=1" >> $GITHUB_ENV
               ;;
             4)
-              echo "_Pull request has performance improvements_" >> comment.md
+              echo "_Pull request has performance improvements ✅_" >> comment.md
               echo "exitStatus=0" >> $GITHUB_ENV
               ;;
             *)
-              echo "_Benchmark comparison failed to complete with exit code $EXIT_CODE_" >> comment.md
+              echo "_Benchmark comparison failed to complete with exit code $EXIT_CODE ❌_" >> comment.md
               echo "exitStatus=1" >> $GITHUB_ENV
               ;;
           esac
